mysql-test:
  container_name: test-mysql
  image: mysql:5.6.23
  restart: always
  ports:
    - "3306:3306"
  environment:
    TZ : "Asia/Shanghai"
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: my-test
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci



